version: "3.9" # optional since v1.27.0
services:
  petit_db_dev:
    image: postgres:14-alpine
    container_name: petit_db_dev
    environment:
      - POSTGRES_USER=petit_user
      - POSTGRES_DB=petit_db_dev
      - POSTGRES_PASSWORD=3263
    ports:
      - 64471:5432
    volumes:
      - petit_vol_dev:/var/lib/postgresql/data


volumes:
  petit_vol_dev:
    driver: local
