version: 2.1
executors:
  ubuntu-default:
    machine:
      image: ubuntu-2004:current
    shell: bash
    environment:
      VERSION: 1.0.0
      REPO: petit
      SERVICE_NAME: petit

commands:
  restore_cache_yarn:
    steps:
      - restore_cache:
          keys:
            - yarn-v1-{{checksum "yarn.lock"}}
            - yarn-v1-

  save_cache_yarn:
    steps:
      - save_cache:
          paths:
            - ./node_modules
          key: yarn-v1-{{checksum "yarn.lock"}}

jobs:
  build_deploy_on_cloud_run:
    executor: ubuntu-default
    steps:
      - checkout

      ####################### BUILD PROJECT ###########################

      - restore_cache_yarn
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache_yarn
      - run:
          name: Build project
          command: |
            npx cqx build
      
      - run: yarn install --prod
      - run:
          name: Copy file in built project
          command: |
            cp -r ./node_modules build/node_modules
            cp Dockerfile-circleci build/
      - run:
          name: Update production database
          command: |
            echo "DATABASE_URL=${DATABASE_URL}" > .env &
            npx prisma migrate deploy &
            npx prisma generate &
          working_directory: build

workflows:
  deploy:
    jobs:
      - build_deploy_on_cloud_run:
          context: 
            - Gcloud
            - cqx